services:
  app:
    image: php:8.3-apache
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./htdocs:/var/www/html
  db:
    image: mariadb:10.5.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - 5050:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
